# Generated by Django 2.1.7 on 2019-04-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['pub_date']},
        ),
    ]
