version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=nse

  db-init:
    build:
      context: .
      dockerfile: docker/dba/Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
